// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLxn4MvX1Ck-aYTK8p9i_NGmHGcacibs',
    appId: '1:527062137540:web:3511e71f6a199aec26a791',
    messagingSenderId: '527062137540',
    projectId: 'healtho-f1635',
    authDomain: 'healtho-f1635.firebaseapp.com',
    storageBucket: 'healtho-f1635.firebasestorage.app',
    measurementId: 'G-NS8MQRMQCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoc-mKgfnq8iJ_jopoeYFez5J7kmIQ7AU',
    appId: '1:527062137540:android:6ef7f43702ae2de126a791',
    messagingSenderId: '527062137540',
    projectId: 'healtho-f1635',
    storageBucket: 'healtho-f1635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFLiIGVlObJaUwxEcg3C9fwA561HXwDU',
    appId: '1:527062137540:ios:7fb0840690ca9f9426a791',
    messagingSenderId: '527062137540',
    projectId: 'healtho-f1635',
    storageBucket: 'healtho-f1635.firebasestorage.app',
    iosBundleId: 'com.example.healthoGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJLxn4MvX1Ck-aYTK8p9i_NGmHGcacibs',
    appId: '1:527062137540:web:6d8c62ed2c1b2d7226a791',
    messagingSenderId: '527062137540',
    projectId: 'healtho-f1635',
    authDomain: 'healtho-f1635.firebaseapp.com',
    storageBucket: 'healtho-f1635.firebasestorage.app',
    measurementId: 'G-K9GS8LJCTK',
  );
}
